### PR TITLE
Implemented EMUN support

### PR DESCRIPTION
**Pull request by aleksey1972**

### CODE REVIEW

**Comment by brasseld** [comment]
Hi @aleksey1972 

Can you fix the conflict ?

**Comment by brasseld** [comment]
Hi @aleksey1972 

Do you want me to do it?
I would like to include this as part of upcoming 3.1

**Comment by aleksey1972** [comment]
Hi!
I made a commit about an hour ago. Is it about him?

**Comment by brasseld** [comment]
Looks there is still a conflict here.
Also, please squash the 2 commits into a single one

**Pull request closed without merging**
